### PR TITLE
feat(d3fc-pointer): type pointer function

### PR DESCRIPTION
**Pull request by johncardiologs**
Attempt to type the main d3fc-pointer function.

I presumed that the [selection object](https://github.com/d3fc/d3fc/blob/b535374943dadd857f9d358e63ffc65f719b9966/packages/d3fc-pointer/src/pointer.js#L18) in the package's [pointer.js](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-pointer/src/pointer.js) file was a D3 selection object, and used its types accordingly

Future work could involve adding type tests, as in [d3fc-chart's typing efforts](https://github.com/d3fc/d3fc/pull/1697). I'm relatively new to TypeScript overall.

### CODE REVIEW

**Comment by murcikan-scottlogic** [comment]
@johncardiologs please fix [build issue](https://app.travis-ci.com/github/d3fc/d3fc/builds/251755340)

**Comment by johncardiologs** [comment]
Done ! @murcikan-scottlogic [9091b9a](https://github.com/d3fc/d3fc/pull/1751/commits/9091b9a31b65e2866fc7b8b68b1ef95e48997901)

**Review by murcikan-scottlogic — COMMENTED** [review]
I'm sorry I have very little experience with defining type files, but do you think you could possibly add tests for the type file just to keep the test coverage high?

**Comment by johncardiologs** [comment]
I unfortunately don't have much experience, let alone with testing. I'll see if I can inspire myself from the tests on the d3fc-chart package though. I was able to type the pointer above by using the [ReturnType method](https://www.typescriptlang.org/docs/handbook/utility-types.html) FYI.

**Comment by johncardiologs** [comment]
Added a few tests. I don't know how much more can be done, given the pointer quite simply expects a `d3.selection` object as input and outputs void.
Also I didn't know how to pass the buildcheck after I committed with a message that commitlint didn't like -- my bad!

**Review by murcikan-scottlogic — APPROVED** [review]

**Comment by murcikan-scottlogic** [comment]
> ... Also I didn't know how to pass the buildcheck after I committed with a message that commitlint didn't like -- my bad!

sorry, just seen this. You could either follow the steps outlined here: https://www.w3docs.com/snippets/git/how-to-change-commit-message.html
or if you find it easier you could abandon this PR and create a new branch, copy your changes over and commit it with an appropriate message

**Comment by johncardiologs** [comment]
I went with option 1 -- build passed! @murcikan-scottlogic

**Review by murcikan-scottlogic — APPROVED** [review]

**Review by johncardiologs — COMMENTED** [review]
Doesn't look like I have permission to merge... @murcikan-scottlogic 
Perhaps the issue is that I cannot request reviews.

**Review by murcikan-scottlogic — APPROVED** [review]

**Pull request closed without merging**
