### PR TITLE
feat: updated dependency versions

### PR DESCRIPTION
**Pull request by msuperina**
Updated dependency versions via ncu --packageFile package.json -u

Includes changes from
- [d3fc-element](https://github.com/d3fc/d3fc-element/releases/tag/v4.0.0) (breaking changes)
- [d3fc-extent](https://github.com/d3fc/d3fc-extent/releases/tag/v2.2.2)
- [d3fc-financial-feed](https://github.com/d3fc/d3fc-financial-feed/releases/tag/v4.0.0)
  (breaking changes)
- [d3fc-random-data](https://github.com/d3fc/d3fc-random-data/releases/tag/v2.0.1)
  (breaking changes)
- [d3fc-sample](https://github.com/d3fc/d3fc-sample/releases/tag/v3.0.5)
- [d3fc-series](https://github.com/d3fc/d3fc-series/releases/tag/v3.2.1)

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Looks like random-data needs a manual intervention to add that tag / release - are there any others?

**Comment by msuperina** [comment]
- d3fc-extent
- d3fc-random-data
- d3fc-sample

**Comment by ColinEberhardt** [comment]
d3fc-sample manually released https://github.com/d3fc/d3fc-sample/releases/tag/v3.0.5

**Comment by ColinEberhardt** [comment]
d3fc-random-data manual release https://github.com/d3fc/d3fc-random-data/releases/tag/v2.0.1

**Comment by ColinEberhardt** [comment]
d3fc-extent manually released https://github.com/d3fc/d3fc-extent/releases/tag/v2.2.2

**Comment by ColinEberhardt** [comment]
Thanks @msuperina - I made a [few tweaks to the README](https://github.com/d3fc/d3fc/pull/1104/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5) and merged - thanks for all your work 👍

**Pull request closed without merging**
