### PR TITLE
feat: Canvas gridline

### PR DESCRIPTION
**Pull request by Ro4052**
#1160 The D3fc annotation package currently only supports SVG. This PR contains an implementation of the the gridline annotation using canvas.

**Note: This has been branched off #1235, as the new implementation is required for this component to work. Edit - This PR has now been merged**

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Now that #1235 has been merged, I'll take a closer look at this :-)

**Comment by Ro4052** [comment]
That sounds great!

**Comment by ColinEberhardt** [comment]
Great job, thanks @Ro4052 - one minor point ...

Can you please add to the README file? See the [d3fc-series README](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-series/README.md#seriesSvgPoint) for how we document svg / canvas

**Comment by Ro4052** [comment]
Hopefully that's roughly what you were looking for with the docs. Let me know of any changes you think are necessary.

**Comment by ColinEberhardt** [comment]
> Hopefully that's roughly what you were looking for with the docs.
Perfect - thank you!

**Pull request merged**
