### PR TITLE
Declaring valueformatter moved after // START tag.

### PR DESCRIPTION
**Pull request by artonevala**
Reader who use introduction page as tutorial and copy&paste code snippets will get undefined valueformatter because declaration is not rendered to doc page.

Moved declaration after // START tag to render it to page. Tested in Ubuntu 16.04 with Firefox and rendering in localhost OK.

### CODE REVIEW

**Comment by chrisprice** [comment]
Thanks for the contribution @artonevala.

**Review by chrisprice — APPROVED** [review]

**Comment by dbarkey-scottlogic** [comment]
@artonevala thanks for the contribution but unfortunately it looks like the build failed. Can you please fix this.

**Comment by artonevala** [comment]
Apologies for the hassles. I have now fixed issue with two consecutive empty lines. Build should be ok now.

**Comment by dbarkey-scottlogic** [comment]
No worries. Thank you.

**Pull request merged**
